#!/usr/bin/env python
"""Generate and validate the release CycloneDX SBOM.

The release SBOM is generated by the upstream ``cyclonedx-bom`` CLI from a
clean Python environment into which the built wheel has been installed.  This
wrapper deliberately does not implement CycloneDX serialization itself: it
adds OVK-specific fail-closed checks around the standards implementation so a
release cannot silently publish an empty, development-environment, or
wrong-version inventory.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any, Sequence

ROOT = Path(__file__).resolve().parents[1]
CYCLONEDX_DISTRIBUTION = "cyclonedx-bom"
CYCLONEDX_SPEC_VERSION = "1.6"
_REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def _normalize_distribution_name(name: str) -> str:
    """Normalize a Python distribution name according to PEP 503 semantics."""

    return re.sub(r"[-_.]+", "-", name).lower()


def _project_metadata(pyproject: Path) -> tuple[str, str, set[str]]:
    """Return project name, version, and normalized direct runtime dependencies."""

    payload = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    project = payload.get("project")
    if not isinstance(project, dict):
        raise ValueError(f"missing [project] table in {pyproject}")

    name = project.get("name")
    version = project.get("version")
    dependencies = project.get("dependencies", [])
    if not isinstance(name, str) or not name.strip():
        raise ValueError(f"missing project.name in {pyproject}")
    if not isinstance(version, str) or not version.strip():
        raise ValueError(f"missing project.version in {pyproject}")
    if not isinstance(dependencies, list) or not all(isinstance(item, str) for item in dependencies):
        raise ValueError(f"project.dependencies must be a list of strings in {pyproject}")

    direct: set[str] = set()
    for requirement in dependencies:
        match = _REQUIREMENT_NAME.match(requirement)
        if match is None:
            raise ValueError(f"cannot determine distribution name from requirement {requirement!r}")
        direct.add(_normalize_distribution_name(match.group(1)))
    return name, version, direct


def _installed_generator_version() -> str:
    """Return the installed upstream CycloneDX generator version."""

    try:
        return importlib.metadata.version(CYCLONEDX_DISTRIBUTION)
    except importlib.metadata.PackageNotFoundError as error:
        raise RuntimeError(
            "cyclonedx-bom is not installed; install the release-pinned generator before running this command"
        ) from error


def _validate_sbom(payload: dict[str, Any], *, pyproject: Path) -> None:
    """Fail closed if the generated SBOM does not describe the release package."""

    project_name, project_version, direct_dependencies = _project_metadata(pyproject)

    if payload.get("bomFormat") != "CycloneDX":
        raise ValueError("generated SBOM is not CycloneDX JSON")
    if payload.get("specVersion") != CYCLONEDX_SPEC_VERSION:
        raise ValueError(
            f"generated SBOM specVersion={payload.get('specVersion')!r}; expected {CYCLONEDX_SPEC_VERSION!r}"
        )

    metadata = payload.get("metadata")
    if not isinstance(metadata, dict):
        raise ValueError("generated SBOM is missing metadata")
    component = metadata.get("component")
    if not isinstance(component, dict):
        raise ValueError("generated SBOM is missing metadata.component")
    if component.get("name") != project_name:
        raise ValueError(
            f"SBOM root component name={component.get('name')!r}; expected {project_name!r}"
        )
    if component.get("version") != project_version:
        raise ValueError(
            f"SBOM root component version={component.get('version')!r}; expected {project_version!r}"
        )

    components = payload.get("components")
    if not isinstance(components, list) or not components:
        raise ValueError("generated SBOM has no installed components")
    component_names = {
        _normalize_distribution_name(str(item["name"]))
        for item in components
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    missing = sorted(direct_dependencies - component_names)
    if missing:
        raise ValueError(
            "generated SBOM is missing direct runtime dependencies: " + ", ".join(missing)
        )

    dependencies = payload.get("dependencies")
    if not isinstance(dependencies, list) or not dependencies:
        raise ValueError("generated SBOM has no dependency graph")


def generate_sbom(
    *,
    target_python: Path,
    output: Path,
    pyproject: Path,
    expected_generator_version: str | None = None,
) -> dict[str, Any]:
    """Generate a reproducible, schema-validated SBOM for ``target_python``."""

    target_python = target_python.resolve()
    output = output.resolve()
    pyproject = pyproject.resolve()
    if not target_python.is_file():
        raise FileNotFoundError(f"target Python interpreter does not exist: {target_python}")
    if not pyproject.is_file():
        raise FileNotFoundError(f"pyproject does not exist: {pyproject}")

    generator_version = _installed_generator_version()
    if expected_generator_version and generator_version != expected_generator_version:
        raise RuntimeError(
            f"cyclonedx-bom version {generator_version!r} does not match required release pin "
            f"{expected_generator_version!r}"
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    command = [
        sys.executable,
        "-m",
        "cyclonedx_py",
        "environment",
        str(target_python),
        "--pyproject",
        str(pyproject),
        "--mc-type",
        "library",
        "--spec-version",
        CYCLONEDX_SPEC_VERSION,
        "--output-format",
        "JSON",
        "--output-reproducible",
        "--validate",
        "--output-file",
        str(output),
    ]
    subprocess.run(command, check=True)

    payload = json.loads(output.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("generated SBOM root must be a JSON object")
    _validate_sbom(payload, pyproject=pyproject)
    return payload


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--python",
        dest="target_python",
        type=Path,
        required=True,
        help="Python interpreter from the clean environment containing the built wheel",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / ".verification" / "release-sbom.cdx.json",
    )
    parser.add_argument("--pyproject", type=Path, default=ROOT / "pyproject.toml")
    parser.add_argument(
        "--expected-generator-version",
        default=None,
        help="Fail unless the installed cyclonedx-bom version exactly matches this pin",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        payload = generate_sbom(
            target_python=args.target_python,
            output=args.output,
            pyproject=args.pyproject,
            expected_generator_version=args.expected_generator_version,
        )
    except (FileNotFoundError, RuntimeError, ValueError, json.JSONDecodeError, subprocess.CalledProcessError) as error:
        print(f"generate_sbom: {error}", file=sys.stderr)
        return 1

    print(
        "generated validated CycloneDX "
        f"{payload['specVersion']} SBOM -> {args.output.resolve()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
